/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as smallProxySol from "./SmallProxy.sol";
export { BoxProxyAdmin__factory } from "./BoxProxyAdmin__factory";
