/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as smallProxySol from "./SmallProxy.sol";
export type { smallProxySol };
export type { BoxProxyAdmin } from "./BoxProxyAdmin";
